version: '3'
services:
  qbittorrent:
    container_name: compose_qbittorrent
    environment:
      - PUID=500
      - PGID=0
      - TZ=Europe/London
      - WEBUI_PORT=6363
    volumes:
      - /share/Configurations/qbittorrent_config:/config
      - /share/Download:/share/CACHEDEV1_DATA/download
    ports:
      - 6363:6363/tcp
      - 6881:6881/tcp
      - 6881:6881/udp
    restart: unless-stopped
    image: lscr.io/linuxserver/qbittorrent:latest

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: compose_jackett
    environment:
      - PUID=500
      - PGID=0
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /share/Configurations/jackett_config:/config
      - /share/Download/torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    depends_on:
      - qbittorrent
    links:
      - qbittorrent

  sonarr:
    container_name: compose_sonarr
    restart: unless-stopped
    ports:
      - 8989:8989/tcp
    volumes:
      - /share/Configurations/sonarr_config:/config
      - /share/Media4TB/TV Series:/tv
      - /share/Download/complete:/share/CACHEDEV1_DATA/download/complete
    environment:
      - PUID=500
      - PGID=0
      - TZ=Europe/London
    image: lscr.io/linuxserver/sonarr:latest
    depends_on:
      - qbittorrent
      - jackett
    links:
      - qbittorrent

  radarr:
    container_name: compose_radarr
    restart: unless-stopped
    ports:
      - 7878:7878/tcp
    volumes:
      - /share/Configurations/radarr_config:/config
      - /share/Media12TB/Movies Library:/movies
      - /share/Media4TB/Movies:/movies4tb
      - /share/Download/complete:/share/CACHEDEV1_DATA/download/complete
    environment:
      - PUID=500
      - PGID=0
      - TZ=Europe/London
    image: lscr.io/linuxserver/radarr:latest
    depends_on:
      - qbittorrent
      - jackett
    links:
      - qbittorrent

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: compose_bazarr
    environment:
      - PUID=500
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Configurations/bazarr_config:/config
      - /share/Media12TB/Movies Library:/movies
      - /share/Media4TB/Movies:/movies4tb
      - /share/Media4TB/TV Series:/tv #optional
    ports:
      - 6767:6767/tcp
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - jackett
    links:
      - qbittorrent

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: compose_flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    links:
      - qbittorrent
